# name: Deploy Api Gateway Service

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'terraform/deployment/api_gateway/**'
#       - '.github/workflows/api_gateway.yml'
#       - 'api_gateway/**'

# permissions:
#   contents: read
#   id-token: write

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     defaults:
#         run:
#             working-directory: terraform/deployment/api_gateway
        

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

      

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
#           aws-region: eu-north-1

#       - name: Set up terraform
#         uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: '1.5.0'

    
#       - name: Terraform Init
#         run: terraform init
        

#       - name: Terraform Plan
#         run: terraform plan -var-file="dev.tfvars"

#       - name: Terraform Apply
#         run: terraform apply -var-file="dev.tfvars" -auto-approve

#       - name: Login to Amazon ECR
#         uses: aws-actions/amazon-ecr-login@v1

      

#       - name: Build and Push Api Gateway Image to ECR
#         run: |
#           docker buildx build --platform linux/amd64 -t api-gateway ../../api_gateway 
#           docker tag api-gateway ${{ secrets.ECR_REGISTRY }}/api-gateway:latest
#           docker push ${{ secrets.ECR_REGISTRY }}/api-gateway:latest

#       - name: Update ECS Service
#         run: |                
#           aws ecs update-service --cluster microservices-app --service api-gateway --force-new-deployment


#       # - name: Terraform destroy
#       #   run: terraform destroy -var-file="dev.tfvars" -auto-approve